name = "TA"
uuid = "293914dc-3181-4e5e-826c-7685ea4e0faa"
authors = ["Anmol Pahwa"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
